### ISSUE TITLE
 `constants_loaded_by': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by tablecell** [jeremyevans/rack-unreloader#11] opened 2021-09-12 03:09 UTC
app.rb
```
require 'nyny'

class App < NYNY::App

   get '/' do
      "some"   
   end 
end 
```

config.ru
```
require  'rack/app'
require  'rack/unreloader'
Unreloader.require './app.rb'
Unreloader = Rack::Unreloader.new{App}

run Unreloader
```

**Comment by jeremyevans** [comment] 2021-09-12 14:41
I'll try to look into this tomorrow.  Seems weird to load both Rack::App and NYNY into the same application, though I'm not sure if that is the cause of the problem.

My guess is the issue could be worked around by doing: `Unreloader.require('./app.rb'){:App}`.  Doing so would also make reloading faster.

**Comment by tablecell** [comment] 2021-09-13 00:23
@jeremyevans
config.ru
```
require  'rack/unreloader'
Unreloader.require('./app.rb'){:App}
run Unreloader

```
 `block in <main>': uninitialized constant Unreloader (NameError)

```
require  'rack/unreloader'

Rack::Unreloader.require('./app.rb'){:App}

run Unreloader
````

`block in <main>': private method `require' called for Rack::Unreloader:Class (NoMethodError)

**Comment by jeremyevans** [comment] 2021-09-13 00:32
I think I can see the problems here.

> ```
> require  'rack/app'
> require  'rack/unreloader'
> Unreloader.require './app.rb'
> Unreloader = Rack::Unreloader.new{App}
> 
> run Unreloader
> ```

Here you are calling `Unreloader.require` before `Unreloader = Rack::Unreloader.new{App}`.  Should be fairly obvious that you need to instantiate the `Unreloader` object first.  Maybe the reason you don't get `NameError` is the `config.ru` is being evaluated inside the `Rack` namespace, or something `Rack::App` is doing.

> ```
> require  'rack/unreloader'
> Unreloader.require('./app.rb'){:App}
> run Unreloader
> ```

Here you are using `Unreloader.require('./app.rb'){:App}` without setting the `Unreloader` constant.

> ```
> require  'rack/unreloader'
> 
> Rack::Unreloader.require('./app.rb'){:App}
> 
> run Unreloader
> ```
> 
> `block in <main>': private method `require' called for Rack::Unreloader:Class (NoMethodError)

Here you are calling `Rack::Unreloader.require`, but you are supposed to call `require` on an instance of `Rack::Unreloader`, not the class itself (it's an instance method, not a class method).  So you end up calling `Kernel#require`, which is private, not public.

So all three of these cases are just incorrectly using the API.  You should follow the example in the README:

```
require 'rack/unreloader'
Unreloader = Rack::Unreloader.new{App}
Unreloader.require './app.rb'

run Unreloader
```

**Comment by tablecell** [comment] 2021-09-13 01:55
with   rack2.0  app rack-unreloader  works  ok 

nyny  3.2  depends on  rack 1.5 
gem depe  nyny -v 3.2.0
```

Gem nyny-3.2.0
  better_errors (~> 1.1.0)
  bundler (~> 1.3, development)
  journey (~> 1.0.4)
  rack (~> 1.5.2)
  rack-contrib (~> 1.1.0)
  rake (>= 0, development)
  rspec (>= 0, development)
  tilt (~> 2.0.0)

```
when webrick start up   visit  url http://localhost:9292/  throw exception
NoMethodError: undefined method `call' for App:Class

  at unreloader.rb line 84       @app_block.call.call(env)

**Comment by jeremyevans** [comment] 2021-09-13 03:56
> with rack2.0 App rack-unreloader works ok
> 
> with rack 1.5 App like nyny/newark , rack-unreloader throw NoMethodError
> 
> when webrick start up visit url http://localhost:9292/ throw NoMethodError
> NoMethodError: undefined method `call' for App:Class
> 
> at unreloader.rb line 84 @app_block.call.call(env)

I'm not sure NYNY supports `call` directly on the class.  You may need to do:

```ruby
require 'nyny'

class AppClass < NYNY::App
   get '/' do
      "some"   
   end 
end 

App = AppClass.new
```

This is unrelated to `rack-unreloader`.  If you are going to post about problems with `rack-unreloader`, please make sure the application works correctly without `rack-unreloader` first.

FWIW, I'm not sure why you would want to create a new application using a web framework that hasn't been updated in 7 years.

**Comment by tablecell** [comment] 2021-09-13 06:00
@jeremyevans

` app = App.new   `  
still  thorw error :
ERROR NameError: uninitialized constant Rack::Request
that means  rack-unreloader is  not compatiable with rack 1.5 

standalone  NYNY works  fine.

use NYNY  for benchmark of   variety   framework   to see  rps  and memeory comsume.

**Comment by jeremyevans** [comment] 2021-09-13 13:44
There is absolutely no reason to use rack-unreloader when benchmarking.  It's designed reloading parts of the application that change in development mode, which is always going to be significantly slower than just serving requests without the need to check for reloading.

rack-unreloader passes all tests on Ruby 1.8.7-3.0.  Here's an example with Ruby 1.8.7 and rack 1.4.5:

```
$ RUBYOPT=-rubygems rake18
/usr/local/bin/ruby18 spec/unreloader_spec.rb
Run options: --seed 14796

# Running:

...............................

Finished in 2.162234s, 14.3370 runs/s, 180.3690 assertions/s.

31 runs, 390 assertions, 0 failures, 0 errors, 0 skips
$ gem18 list rack

*** LOCAL GEMS ***

rack (1.4.5, 1.4.1, 1.4.0, 1.3.2, 1.1.0, 1.0.1, 0.9.1)
```

So it doesn't have any problems with rack before 2.0.

I'm going to close this now.  All of the previous issues posted in this ticket are related to not using the rack-unreloader API correctly, or having problems setting up a web framework.  If you think there is an actual bug with rack-unreloader, please post evidence of that.

**Closed by jeremyevans** 2021-09-13 13:44 UTC
